numbers = set()

num = int(input("Enter the number: "))
numbers.add(num)
num = int(input("Enter the number: "))
numbers.add(num)
num = int(input("Enter the number: "))
numbers.add(num)
num = int(input("Enter the number: "))
numbers.add(num)
num = int(input("Enter the number: "))
numbers.add(num)
num = int(input("Enter the number: "))
numbers.add(num)
num = int(input("Enter the number: "))
numbers.add(num)
num = int(input("Enter the number: "))
numbers.add(num)

print(numbers)